# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:

- task: Docker@2
  displayName: Build image
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'portfolio-front'
    command: 'build'
    Dockerfile: '**/prod.Dockerfile'
    tags: 'latest'
    arguments: 'artifacts_folder=src'

- task: Docker@2
  displayName: Push image to dockerhub
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'portfolio-front'
    command: 'push'
    tags: 'latest'