version: '3.9'

services:
  web:
    container_name: portfolio-front
    image: apallis/portfolio-front:latest
    ports:
      - 5002:80
    restart: unless-stopped
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GIN_MODE
